### ISSUE TITLE
UX improvements: tidy up hover infobox for points

### ISSUE THREAD

**Issue by kidwellj** [mapcomm/common-ground_map#2]
Let's make font boldface and larger (50% bigger) for place name

**Comment by danhillcode** [comment]
Sorted but this needs checking for size.

**Comment by danhillcode** [comment]
also centered the text which looks tidy.

**Comment by kidwellj** [comment]
Nearly there - I like having things centred. Can we reduce padding around the top/bottom by 50%, shrink the space inbetween the two lines by 25%, and make the "click for more information" italics rather than bold?

**Comment by danhillcode** [comment]
some issues with prune cluster and hover but should be fine just needs more research.

**Comment by danhillcode** [comment]
fixed it can you check that you are happy with the design of this before closing the issue thanks

**Comment by danhillcode** [comment]
thoughts on this one, if changes needed can we sort them in the next meeting?

**Comment by danhillcode** [comment]
Are you happy with the style of this now can we close this?

**Comment by kidwellj** [comment]
The UX on these boxes still isn't quite right. Position of box makes it difficult to click to bring up "information window" on the right. Can we raise it at least 20px and see if it gets easier to click on the point? We should also add text to the hover window to lead user on this: "click on marker for more information" Should be an easy instruction to follow once the box isn't covering the marker I think.
